#!/usr/bin/env php
<?php

use MeetupOrganizing\Infrastructure\Cli\MeetupApplicationConfig;
use MeetupOrganizing\Infrastructure\ServiceContainer;
use Webmozart\Console\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';

$container = new ServiceContainer(__DIR__);

$cli = new ConsoleApplication(new MeetupApplicationConfig($container));
$cli->run();
