#!/usr/bin/env php
<?php

use Meetup\Infrastructure\MeetupApplication;
use Meetup\Infrastructure\MeetupApplicationConfig;
use Webmozart\Console\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';

$cli = new ConsoleApplication(new MeetupApplicationConfig(new MeetupApplication()));
$cli->run();
